# === Request ===

# Absolute path to map_directory
string bosdyn_map_filepath 

# Waypoint id string for where to go
string waypoint_id 

# Tells the initializer whether to use fiducials
bool initial_localization_fiducial   

# Waypoint id to trigger localization 
string initial_localization_waypoint 

---

# === Response ===

# indicate successful run of triggered service
bool success   

# informational, e.g. for error messages
string message 

---

# === Feedback ===

string feedback

