twist_mux:
  ros__parameters:
    topics:
      controller:
        topic   : controller/cmd_vel
        timeout : 0.5
        priority: 9
      keyboard:
        topic   : keyboard/cmd_vel
        timeout : 0.5
        priority: 8
      hololens:
        topic   : hololens/cmd_vel
        timeout : 0.5
        priority: 7

