# This is an example config for a certain tag. Create a copy of this file and edit it for your specific needs; do not delete this template.
/**:                 # node name
  ros__parameters:
    # setup (defaults)
    image_transport: raw  # image format: "raw" or "compressed"
    family: 'Standard52h13'         # tag family name: 16h5, 25h9, 36h11
    z_up: false

    # tuning of detection (defaults)
    max_hamming: 3        # maximum allowed hamming distance (corrected bits)
    detector:
      threads: 4          # number of threads
      decimate: 1.5       # decimate resolution for quad detection
      blur: 0.0           # sigma of Gaussian blur for quad detection
      refine: false       # snap to strong gradients
      sharpening: 0.25 # sharpening of decoded images

    publish_tf: true            # Publish TF frames for detected tag(s)

    # (optional) list of tags
    # If defined, 'frames' and 'sizes' must have the same length as 'ids'.
    tag:
      ids:    [7, 0]         # tag IDs for which to publish transform
      frames: [affordance_frame, trashcan_frame]   # frame names
      sizes:  [0.057, 0.055]     # tag-specific edge size, overrides the default 'size'
