spot_image_server:
  ros__parameters:
    rates:
      frontleft:
        rgb: 10
        depth: 10
      frontright:
        rgb: 10
        depth: 10
      left:
        rgb: 10
        depth: 10
      right:
        rgb: 10
        depth: 10
      back:
        rgb: 10
        depth: 10
      hand_rgb:
        rgb: 10
        depth: 10
      hand_tof:
        rgb: 10
        depth: 10
