/spot_driver:
  ros__parameters:
    has_eap: true
    has_arm: true
    auto_claim: false
    auto_power_on: false
    auto_stand: false

    rates:
      sensors:
        point_cloud: 10.0
      status:
        robot_state: 20.0
        lease: 1.0
    
    estop_timeout: 9.0
    odom_mode: vision
